# This config is supposed to be run with RHEL 8.2
# and deploy OSP 16.1
# Before running provision.sh, you need to override
# the image name:
# $ export IMAGE_NAME=RHEL-8.2.0-x86_64-latest
# $ ./provision.sh kuryr-cloud
create_rhcos_image: false
hostname: kuryr-cloud
clouddomain: ci.vexxhost.ca
ceph_devices:
  - /dev/sdc
local_cloudname: kuryr-cloud
rhsm_enabled: true
