create_rhcos_image: false
hostname: kuryr-cloud-train
clouddomain: ci.vexxhost.ca
control_plane_ip: 38.129.56.112
ceph_devices:
  - /dev/sdc
tripleo_repos_branch: train
# tripleo-repos only supports --stream (for CentOS 8 Stream) after Train,
# so we need to pull tripleo-repos tool from master and move on.
tripleo_repos_repo_branch: master
cip_config:
  - set:
      namespace: quay.io/tripleotraincentos8
      name_prefix: centos-binary-
      tag: current-tripleo
authorized_keys:
  - https://github.com/EmilienM.keys
  - https://github.com/MaysaMacedo.keys
