# This config is supposed to be run with RHEL 8.2
# and deploy OSP 16.1
# Before running provision.sh, you need to override
# the image name:
# $ export IMAGE_NAME=RHEL-8.2.0-x86_64-latest
# $ ./provision.sh kuryr-cloud
clouddomain: ci.vexxhost.ca
ceph_devices:
  - /dev/sdc
rhsm_enabled: true
external_cidr: 38.129.56.0/24
external_fip_pool_start: 38.129.56.2
external_fip_pool_end: 38.129.56.42
external_gateway: 38.129.56.1
