clouddomain: ci.vexxhost.ca
ceph_devices: true
ephemeral_storage_devices:
- /dev/sdc
- /dev/sdd
octavia_enabled: false
dcn_az: az0
local_ip: 192.168.24.10
control_plane_ip: 192.168.24.11
hostonly_gateway: 192.168.25.2
tunnel_remote_ips:
  - 38.102.83.91
tripleo_repos_repos:
  - current-tripleo-dev
  - ceph
