clouddomain: ci.vexxhost.ca
manila_enabled: true
ceph_devices:
  - /dev/sdb
ephemeral_storage_devices:
  - /dev/sdc
  - /dev/sdd
swiftoperator_enabled: false
rhsm_enabled: true
standalone_extra_config:
  octavia::wsgi::apache:workers: 4
  tripleo::firewall::firewall_rules:
    '168 allow squid':
      dport: 3128
      proto: tcp
      action: accept
dpdk_interface: enp193s0f1
kernel_args: "default_hugepagesz=1GB hugepagesz=1G hugepages=384 iommu=pt amd_iommu=on isolcpus=8-95"
tuned_isolated_cores: "8-95"
extra_heat_params:
  NovaComputeCpuDedicatedSet: ['8-95']
  NovaReservedHostMemory: 4096
  NovaComputeCpuSharedSet: [0,1,2,3,4,5,6,7]
  OvsDpdkSocketMemory: "2048,2048"
  OvsPmdCoreList: "8,9"
post_install: |
  sudo dnf install -y wget
  export OS_CLOUD=standalone
  openstack subnet set hostonly-subnet --no-allocation-pool --allocation-pool start=192.168.25.2,end=192.168.25.127
  openstack subnet set hostonly-subnet --tag no_dhcp_range=192.168.25.128/25
  for i in m1.xlarge m1.large.nodisk m1.xlarge.nodisk m1.large m1.medium m1.tiny m1.small; do openstack flavor set --no-property --property hw:mem_page_size=large $i; done
  openstack image show centos8-stream || wget https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20210210.0.x86_64.qcow2 && openstack image create --public --disk-format qcow2 --file CentOS-Stream-GenericCloud-8-20210210.0.x86_64.qcow2 centos8-stream && rm -f CentOS-Stream-GenericCloud-8-20210210.0.x86_64.qcow2
  openstack quota set --cores 86 \
          --fixed-ips -1 \
          --injected-file-size -1 \
          --injected-files -1 \
          --instances -1 \
          --key-pairs -1 \
          --properties -1 \
          --ram 300000 \
          --gigabytes 1000 \
          --server-groups -1 \
          --server-group-members -1 \
          --backups -1 \
          --backup-gigabytes -1 \
          --per-volume-gigabytes -1 \
          --snapshots -1 \
          --volumes -1 \
          --floating-ips 10 \
          --secgroup-rules -1 \
          --secgroups -1 \
          --networks -1 \
          --subnets -1 \
          --ports -1 \
          --routers -1 \
          --rbac-policies -1 \
          --subnetpools -1 \
          openshift
  sudo podman create --net=host --name=squid --volume /home/stack/squid/squid.conf:/etc/squid/squid.conf:z --volume /home/stack/squid/htpasswd:/etc/squid/htpasswd:z quay.io/emilien/squid:latest
  sudo podman generate systemd --name squid | sudo tee -a /etc/systemd/system/container-squid.service
  sudo systemctl enable --now container-squid
