clouddomain: ci.vexxhost.ca
ceph_devices:
  - /dev/sdc
octavia_enabled: false
dcn_az: az0
rhsm_enabled: true
local_ip: 192.168.24.10
control_plane_ip: 192.168.24.11
hostonly_gateway: 192.168.25.2
tunnel_remote_ips:
  - 38.102.83.222
