clouddomain: ci.vexxhost.ca
ceph_devices:
  - /dev/sdc
manila_enabled: true
dcn_az: central
rhsm_enabled: true
external_cidr: 38.129.56.0/24
external_fip_pool_start: 38.129.56.43
external_fip_pool_end: 38.129.56.83
external_gateway: 38.129.56.1
